require("src.plugins-setup")  -- should be at the top
require("src.core.options")
require("src.core.keymaps")
require("src.core.colorscheme")
require("src.plugins.comment")
require("src.plugins.nvim-tree")
require("src.plugins.lualine")
require("src.plugins.telescope")
require("src.plugins.nvim-cmp")
require("src.plugins.lsp.mason")
require("src.plugins.lsp.lspsaga")
require("src.plugins.lsp.lspconfig")
require("src.plugins.lsp.null-ls")
require("src.plugins.autopairs")
require("src.plugins.treesitter")
require("src.plugins.gitsigns")
